language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.9.1
    - otp_release: 21.0
      elixir: 1.8.2
script:
  - mix format --check-formatted
  # - mix test
addons:
  apt:
    packages:
      - pkgconf
      - libglfw3
      - libglfw3-dev
      - libglew1.13
      - libglew-dev
